"""trip lifecycle status changes

Revision ID: 50cac8546234
Revises: 
Create Date: 2026-06-20 11:38:59.755230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50cac8546234'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index('ix_expenses_trip_date', ['trip_id', 'date'], unique=False)
        batch_op.create_index('ix_expenses_trip_paid', ['trip_id', 'paid_by_id'], unique=False)

    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.create_index('ix_settlements_trip_payee', ['trip_id', 'payee_id'], unique=False)
        batch_op.create_index('ix_settlements_trip_payer', ['trip_id', 'payer_id'], unique=False)

    with op.batch_alter_table('trip_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_confirmed', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('confirmed_at', sa.DateTime(), nullable=True))
        batch_op.create_index('ix_trip_members_trip_status', ['trip_id', 'status'], unique=False)
        batch_op.create_index('ix_trip_members_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_unique_constraint('uq_trip_member', ['trip_id', 'user_id'])

    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmation_deadline', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('confirmation_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))
        batch_op.create_index('ix_trips_owner_status', ['owner_id', 'status'], unique=False)
        batch_op.create_index('ix_trips_public_start', ['is_public', 'start_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_index('ix_trips_public_start')
        batch_op.drop_index('ix_trips_owner_status')
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('confirmation_started_at')
        batch_op.drop_column('confirmation_deadline')

    with op.batch_alter_table('trip_members', schema=None) as batch_op:
        batch_op.drop_constraint('uq_trip_member', type_='unique')
        batch_op.drop_index('ix_trip_members_user_status')
        batch_op.drop_index('ix_trip_members_trip_status')
        batch_op.drop_column('confirmed_at')
        batch_op.drop_column('is_confirmed')

    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.drop_index('ix_settlements_trip_payer')
        batch_op.drop_index('ix_settlements_trip_payee')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index('ix_expenses_trip_paid')
        batch_op.drop_index('ix_expenses_trip_date')

    # ### end Alembic commands ###
