"""add api_key to users

Revision ID: d7beffce4e37
Revises: a1b2c3d4e5f6
Create Date: 2026-06-21 11:44:05.154620

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd7beffce4e37'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_api_key'), ['api_key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_api_key'))
        batch_op.drop_column('api_key')

    # ### end Alembic commands ###
